[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "5b62c899cf8329a8d07e8fe6eda96039010046c7"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[MPICH.download]]
    sha256 = "5ca68bb1561dbaa88d57f6577c01c8ee174cd0621fe6e2722351449ce0143d95"
    url = "https://github.com/boriskaus/MPICH_jll.jl/releases/download/MPICH-v4.2.3+1/MPICH.v4.2.3.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "06525cf290d1773471fa580194590ff85b6d4870"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MPICH.download]]
    sha256 = "fd1167afdcb3986cb93d0a7977e6e94ac3a1654966c03c9a089baba3095ec853"
    url = "https://github.com/boriskaus/MPICH_jll.jl/releases/download/MPICH-v4.2.3+1/MPICH.v4.2.3.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
