[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "ab08b4733984749265932af25afc35f2f48e3def"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MPICH.download]]
    sha256 = "1ad9f320b74ee43c6aa3a245004d9fe1ae205fcd5a7534276d6015b08b0f2eb1"
    url = "https://github.com/boriskaus/MPICH_jll.jl/releases/download/MPICH-v4.2.3+0/MPICH.v4.2.3.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
